on: [push, pull_request]
env:
  CFG_RELEASE: nightly
  CFG_RELEASE_CHANNEL: nightly
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: git clone
      uses: actions/checkout@v2
    - name: install rust nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: unit tests
      run: cargo test --lib
    - name: git clone OAI/OpenAPI-Specification
      uses: actions/checkout@v2
      with:
        repository: OAI/OpenAPI-Specification
    - name: integration tests openapi_spec_examples
      run: cargo test --test openapi_spec_examples